metadata:
  title: КОНФИГУРАЦИОННОЕ УПРАВЛЕНИЕ
  author: П.Н. Советов
  date: Москва – 2021
  figureTitle: Рис. 
  figPrefix: рис.
  titleDelim: .
  tableTitle: Таблица
  tblPrefix: табл. 
  numberSections: true
  sectionsDepth: 3
  secHeaderDelim: ". "
  toc-title: Оглавление
